-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

function hex_to_rgb(hex)
  if hex == nil or hex == "NONE" then
    return { r = 0, g = 0, b = 0 }
  end
  hex = string.lower(hex)
  return {
    r = tonumber(hex:sub(2, 3), 16) or 0,
    g = tonumber(hex:sub(4, 5), 16) or 0,
    b = tonumber(hex:sub(6, 7), 16) or 0,
  }
end
function rgb_to_hex(rgb)
  local r = math.max(0, math.min(255, math.floor(rgb.r + 0.5)))
  local g = math.max(0, math.min(255, math.floor(rgb.g + 0.5)))
  local b = math.max(0, math.min(255, math.floor(rgb.b + 0.5)))
  return string.format("#%02x%02x%02x", r, g, b)
end
function parse_hex8(hex8)
  if hex8 == nil or #hex8 ~= 9 then
    return hex8 or "#000000", 1.0
  end
  local hex6 = hex8:sub(1, 7)
  local alpha = tonumber(hex8:sub(8, 9), 16) / 255
  return hex6, alpha
end

function blend(foreground, alpha, background)
  if foreground == "NONE" then
    return "NONE"
  end

  background = background or "#000000"
  if background == "NONE" then
    background = "#000000"
  end

  local fg = hex_to_rgb(foreground)
  local bg = hex_to_rgb(background)

  local blended = {
    r = (1 - alpha) * bg.r + alpha * fg.r,
    g = (1 - alpha) * bg.g + alpha * fg.g,
    b = (1 - alpha) * bg.b + alpha * fg.b,
  }

  return rgb_to_hex(blended)
end
function lighten(hex, amount)
  if hex == "NONE" then
    return hex
  end

  local rgb = hex_to_rgb(hex)

  return rgb_to_hex({
    r = rgb.r + amount,
    g = rgb.g + amount,
    b = rgb.b + amount,
  })
end
function darken(hex, amount)
  return lighten(hex, -amount)
end
function rgba(r, g, b, alpha, background)
  local bg = hex_to_rgb(background or "#000000")

  local blended = {
    r = (1 - alpha) * bg.r + alpha * r,
    g = (1 - alpha) * bg.g + alpha * g,
    b = (1 - alpha) * bg.b + alpha * b,
  }

  return rgb_to_hex(blended)
end
function extend_hex8(hex8, background)
  if hex8 == nil or #hex8 ~= 9 then
    return hex8 or "#000000"
  end
  local hex6, alpha = parse_hex8(hex8)
  return blend(hex6, alpha, background)
end

-- background = "#1d1e19"
-- black = "#272822"
-- dark1 = "#272822"
-- dark2 = "#1d1e19"
-- text = "#f5f4f1"
-- accent1 = "#f92672"
-- accent2 = "#66d9ef"
-- accent3 = "#e6db74"
-- accent4 = "#a6e22e"
-- accent5 = "#9effff"
-- accent6 = "#ae81ff"
-- accent7 = "#fd971f"
-- accent8 = "#c40000"
-- dimmed1 = "#6e7066"
-- dimmed2 = "#5d5e58"
-- dimmed3 = "#4b4c45"
-- dimmed4 = "#3a3b35"
-- dimmed5 = "#30312b"

-- dark2 = "#272822",
-- dark1 = "#383830",
-- background = "#1d1e19",
-- dimmed1 = "#c0c1b5",
-- dimmed2 = "#919288",
-- dimmed3 = "#6e7066",
-- dimmed4 = "#57584f",
-- dimmed5 = "#3b3c35",

local csbase = {
  text = "#f9f8f5",
  background = "#1d1e19",
  black = "#272822",
  dark = "#383830",
  red = "#c40000",
  neon_red = "#f92672",
  orange = "#fd971f",
  yellow = "#e6db74",
  green = "#a6e22e",
  blue = "#66d9ef",
  cyan = "#a1efe4",
  magenta = "#ae81ff",
  dimmed1 = "#c0c1b5",
  dimmed2 = "#a59f85",
  dimmed3 = "#919288",
  dimmed4 = "#75715e",
  dimmed5 = "#6e7066",
  dimmed6 = "#5d5e58",
  dimmed7 = "#49483e",
  dimmed8 = "#3b3c35",
}
-- base00 #272822
-- base01 #383830
-- base02 #49483e
-- base03 #75715e
-- base04 #a59f85
-- base05 #f8f8f2
-- base06 #f5f4f1
-- base07 #f9f8f5
-- base08 #f92672
-- base09 #fd971f
-- base0A #f4bf75
-- base0B #a6e22e
-- base0C #a1efe4
-- base0D #66d9ef
-- base0E #ae81ff
-- base0F #cc6633


if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "midnightokai"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = csbase.cyan })
hi(0, "@attribute", { fg = csbase.green })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { fg = csbase.magenta })
hi(0, "@character", { fg = csbase.yellow })
hi(0, "@character.printf", { fg = csbase.yellow })
hi(0, "@character.special", { fg = csbase.yellow })
hi(0, "@comment.documentation.lua", { fg = csbase.cyan })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@conceal.markdown", { bg = csbase.dark })
hi(0, "@conditional.lua", { fg = csbase.neon_red })
hi(0, "@constant", { fg = csbase.magenta })
hi(0, "@constant.builtin", { fg = csbase.magenta })
hi(0, "@constant.cpp", { fg = csbase.cyan })
hi(0, "@constant.macro", { fg = csbase.magenta })
hi(0, "@constant.macro.cpp", { fg = csbase.neon_red })
hi(0, "@constructor", { fg = csbase.neon_red })
hi(0, "@constructor.python", { fg = csbase.orange })
hi(0, "@diff.delta", { fg = csbase.yellow })
hi(0, "@diff.minus", { fg = csbase.neon_red })
hi(0, "@diff.plus", { fg = csbase.green })
hi(0, "@exception.python", { fg = csbase.neon_red })
hi(0, "@field", { fg = csbase.neon_red })
hi(0, "@field.lua", { fg = csbase.text })
hi(0, "@function", { fg = csbase.orange })
hi(0, "@function.attribute", { fg = csbase.green })
hi(0, "@function.builtin", { fg = csbase.cyan })
hi(0, "@function.builtin.bash", { fg = csbase.text })
hi(0, "@function.builtin.lua", { fg = csbase.orange })
hi(0, "@function.call", { fg = csbase.green })
hi(0, "@function.call.bash", { fg = csbase.text })
hi(0, "@function.macro", { fg = csbase.green })
hi(0, "@function.method", { fg = csbase.orange })
hi(0, "@function.method.call", { fg = csbase.green })
hi(0, "@ibl.indent.char.1", { fg = csbase.dimmed6, nocombine = true })
hi(0, "@ibl.scope.char.1", { bg = "#31322c", fg = "#b4b5a9", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#b4b5a9", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = csbase.dimmed6, nocombine = true })
hi(0, "@keyword", { fg = csbase.neon_red })
hi(0, "@label", { fg = csbase.cyan })
hi(0, "@markup", { fg = csbase.text })
hi(0, "@markup.emphasis", { fg = csbase.text })
hi(0, "@markup.environment", { fg = csbase.text })
hi(0, "@markup.environment.name", { fg = csbase.text })
hi(0, "@markup.heading", { bold = true, fg = csbase.green })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#151612", fg = "#151612", nocombine = true, sp = csbase.text, underdouble = true })
hi(0, "@markup.heading.1.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.1.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#151612", fg = "#151612", nocombine = true, sp = csbase.text, underline = true })
hi(0, "@markup.heading.2.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.2.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.3.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.3.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.4.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.4.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.5.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.5.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.6.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.6.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.7.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.7.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.8.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.8.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.heading.9.markdown", { fg = csbase.yellow })
hi(0, "@markup.heading.9.marker.markdown", { fg = csbase.dimmed3 })
hi(0, "@markup.italic", { fg = csbase.text, italic = true })
hi(0, "@markup.italic.markdown_inline", { italic = true })
hi(0, "@markup.link", { fg = csbase.blue, underline = true })
hi(0, "@markup.link.label", { fg = csbase.blue, underline = true })
hi(0, "@markup.link.label.markdown_inline", { fg = csbase.neon_red })
hi(0, "@markup.link.label.symbol", { fg = csbase.blue, underline = true })
hi(0, "@markup.link.url", { fg = csbase.blue, underline = true })
hi(0, "@markup.link.url.markdown_inline", { fg = csbase.green, underline = true })
hi(0, "@markup.list", { fg = csbase.text })
hi(0, "@markup.list.checked", { fg = csbase.text })
hi(0, "@markup.list.markdown", { fg = csbase.text })
hi(0, "@markup.list.unchecked", { fg = csbase.text })
hi(0, "@markup.math", { fg = csbase.yellow })
hi(0, "@markup.raw", { fg = csbase.yellow })
hi(0, "@markup.raw.block.markdown", { bg = csbase.dark })
hi(0, "@markup.raw.delimiter.markdown", { bg = csbase.dark, fg = csbase.dimmed3 })
hi(0, "@markup.raw.markdown_inline", { fg = csbase.yellow })
hi(0, "@markup.strikethrough", { fg = csbase.text, strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = csbase.text })
hi(0, "@markup.strong.markdown_inline", { bold = true })
hi(0, "@markup.underline", { fg = csbase.text, underline = true })
hi(0, "@method.python", { fg = csbase.orange })
hi(0, "@module", { fg = csbase.cyan })
hi(0, "@module.builtin", { fg = csbase.cyan })
hi(0, "@namespace.builtin", { fg = csbase.cyan })
hi(0, "@namespace.cpp", { fg = csbase.green })
hi(0, "@namespace.lua", { fg = csbase.neon_red })
hi(0, "@none.markdown", { bg = csbase.dark })
hi(0, "@number", { fg = csbase.magenta })
hi(0, "@operator", { fg = csbase.neon_red })
hi(0, "@operator.cpp", { fg = csbase.neon_red })
hi(0, "@parameter", { fg = csbase.cyan })
hi(0, "@parameter.bash", { fg = csbase.text })
hi(0, "@parameter.lua", { fg = csbase.orange })
hi(0, "@parameters", { fg = csbase.cyan })
hi(0, "@property", { fg = csbase.green })
hi(0, "@property.yaml", { fg = csbase.neon_red })
hi(0, "@punctuation.bracket", { fg = csbase.neon_red })
hi(0, "@punctuation.delimiter", { fg = csbase.text })
hi(0, "@punctuation.special", { fg = csbase.dimmed3 })
hi(0, "@punctuation.special.latex", { fg = csbase.neon_red })
hi(0, "@punctuation.special.markdown", { fg = csbase.dimmed3 })
hi(0, "@punctuation.special.yaml", { fg = csbase.text })
hi(0, "@string", { fg = csbase.yellow })
hi(0, "@string.documentation", { fg = csbase.dimmed5 })
hi(0, "@string.escape", { fg = csbase.magenta })
hi(0, "@string.latex", { fg = csbase.cyan })
hi(0, "@string.regexp", { fg = csbase.yellow })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag", { fg = csbase.neon_red })
hi(0, "@tag.attribute", { fg = csbase.cyan })
hi(0, "@tag.builtin", { fg = csbase.neon_red })
hi(0, "@tag.delimiter", { fg = csbase.text })
hi(0, "@text.emphasis.latex", {})
hi(0, "@text.emphasis.markdown_inline", { fg = csbase.text })
hi(0, "@text.environment.latex", { fg = csbase.green })
hi(0, "@text.environment.name.latex", { fg = csbase.orange })
hi(0, "@text.literal.block.markdown", { bg = "#151612" })
hi(0, "@text.literal.markdown_inline", { bg = csbase.dimmed6, fg = csbase.text })
hi(0, "@text.math.latex", { fg = csbase.magenta })
hi(0, "@text.quote.markdown", { bg = csbase.dimmed8, fg = csbase.text })
hi(0, "@text.reference.markdown_inline", { fg = csbase.neon_red })
hi(0, "@text.strong.latex", {})
hi(0, "@text.strong.markdown_inline", { fg = csbase.text })
hi(0, "@text.uri.markdown_inline", { fg = csbase.green, sp = csbase.green, underline = true })
hi(0, "@type", { fg = csbase.orange })
hi(0, "@type.builtin", { fg = csbase.neon_red })
hi(0, "@type.cpp", { fg = csbase.cyan })
hi(0, "@type.definition", { fg = csbase.green })
hi(0, "@type.python", { fg = csbase.orange })
hi(0, "@variable", { fg = csbase.text })
hi(0, "@variable.builtin", { fg = csbase.blue })
hi(0, "@variable.builtin.bash", { fg = csbase.orange })
hi(0, "@variable.member", { fg = csbase.text })
hi(0, "@variable.member.python", { fg = csbase.green })
hi(0, "@variable.parameter", { fg = csbase.cyan })
hi(0, "@variable.parameter.bash", { fg = csbase.text })
hi(0, "AerialArray", { fg = csbase.magenta })
hi(0, "AerialBoolean", { fg = csbase.magenta })
hi(0, "AerialClass", { fg = csbase.cyan })
hi(0, "AerialConstant", { fg = csbase.magenta })
hi(0, "AerialConstructor", { fg = csbase.green })
hi(0, "AerialEnum", { fg = csbase.cyan })
hi(0, "AerialEnumMember", { fg = csbase.magenta })
hi(0, "AerialEvent", { fg = csbase.cyan })
hi(0, "AerialField", { fg = csbase.text })
hi(0, "AerialFile", { fg = csbase.green })
hi(0, "AerialFunction", { fg = csbase.green })
hi(0, "AerialInterface", { fg = csbase.green })
hi(0, "AerialKey", { fg = csbase.magenta })
hi(0, "AerialLine", { bg = "#664316" })
hi(0, "AerialMethod", { fg = csbase.green })
hi(0, "AerialModule", { fg = csbase.cyan })
hi(0, "AerialNamespace", { fg = csbase.text })
hi(0, "AerialNull", { fg = csbase.neon_red })
hi(0, "AerialNumber", { fg = csbase.magenta })
hi(0, "AerialObject", { fg = csbase.magenta })
hi(0, "AerialOperator", { fg = csbase.neon_red })
hi(0, "AerialPackage", { fg = csbase.cyan })
hi(0, "AerialProperty", { fg = csbase.cyan })
hi(0, "AerialString", { fg = csbase.yellow })
hi(0, "AerialStruct", { fg = csbase.cyan })
hi(0, "AerialTypeParameter", { fg = csbase.neon_red })
hi(0, "AerialVariable", { fg = csbase.text })
hi(0, "AlphaButton", { fg = csbase.magenta })
hi(0, "AlphaFooter", { fg = csbase.blue })
hi(0, "AlphaHeader", { fg = csbase.yellow })
hi(0, "Beacon", { bg = csbase.blue })
hi(0, "BlinkCmpGhostText", { link = "Comment" })
hi(0, "BlinkCmpKind", { fg = "#b1b2a6" })
hi(0, "BlinkCmpKindArray", { fg = csbase.neon_red })
hi(0, "BlinkCmpKindBoolean", { fg = csbase.neon_red })
hi(0, "BlinkCmpKindClass", { fg = csbase.cyan })
hi(0, "BlinkCmpKindColor", { fg = csbase.magenta })
hi(0, "BlinkCmpKindConstant", { fg = csbase.magenta })
hi(0, "BlinkCmpKindConstructor", { fg = csbase.green })
hi(0, "BlinkCmpKindEnum", { fg = csbase.blue })
hi(0, "BlinkCmpKindEnumMember", { fg = csbase.blue })
hi(0, "BlinkCmpKindEvent", { fg = csbase.blue })
hi(0, "BlinkCmpKindField", { fg = csbase.blue })
hi(0, "BlinkCmpKindFile", { fg = csbase.red })
hi(0, "BlinkCmpKindFolder", { fg = csbase.red })
hi(0, "BlinkCmpKindFunction", { fg = csbase.green })
hi(0, "BlinkCmpKindInterface", { fg = csbase.cyan })
hi(0, "BlinkCmpKindKey", { fg = csbase.blue })
hi(0, "BlinkCmpKindKeyword", { fg = csbase.neon_red })
hi(0, "BlinkCmpKindMethod", { fg = csbase.green })
hi(0, "BlinkCmpKindModule", { fg = csbase.cyan })
hi(0, "BlinkCmpKindNamespace", { fg = csbase.cyan })
hi(0, "BlinkCmpKindNull", { fg = csbase.magenta })
hi(0, "BlinkCmpKindNumber", { fg = csbase.magenta })
hi(0, "BlinkCmpKindObject", { fg = csbase.cyan })
hi(0, "BlinkCmpKindOperator", { fg = csbase.neon_red })
hi(0, "BlinkCmpKindPackage", { fg = csbase.magenta })
hi(0, "BlinkCmpKindProperty", { fg = csbase.blue })
hi(0, "BlinkCmpKindReference", { fg = csbase.magenta })
hi(0, "BlinkCmpKindSnippet", { fg = csbase.green })
hi(0, "BlinkCmpKindString", { fg = csbase.yellow })
hi(0, "BlinkCmpKindStruct", { fg = csbase.neon_red })
hi(0, "BlinkCmpKindText", { fg = csbase.yellow })
hi(0, "BlinkCmpKindTypeParameter", { fg = csbase.blue })
hi(0, "BlinkCmpKindUnit", { fg = csbase.magenta })
hi(0, "BlinkCmpKindVariable", { fg = csbase.cyan })
hi(0, "BlinkCmpLabel", { fg = "#b1b2a6" })
hi(0, "BlinkCmpLabelDeprecated", { strikethrough = true })
hi(0, "BlinkCmpLabelDescription", { fg = "#c3c4b8" })
hi(0, "BlinkCmpLabelMatch", { fg = csbase.text })
hi(0, "BlinkCmpMenu", { bg = csbase.dimmed8, fg = "#b1b2a6" })
hi(0, "BlinkCmpSource", { fg = csbase.dimmed1 })
hi(0, "Boolean", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsArray", { fg = csbase.neon_red })
hi(0, "BreadcrumbIconsBoolean", { fg = csbase.neon_red })
hi(0, "BreadcrumbIconsClass", { fg = csbase.cyan })
hi(0, "BreadcrumbIconsColor", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsConstant", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsConstructor", { fg = csbase.green })
hi(0, "BreadcrumbIconsEnum", { fg = csbase.blue })
hi(0, "BreadcrumbIconsEnumMember", { fg = csbase.blue })
hi(0, "BreadcrumbIconsEvent", { fg = csbase.blue })
hi(0, "BreadcrumbIconsField", { fg = csbase.blue })
hi(0, "BreadcrumbIconsFile", { fg = csbase.red })
hi(0, "BreadcrumbIconsFolder", { fg = csbase.red })
hi(0, "BreadcrumbIconsFunction", { fg = csbase.green })
hi(0, "BreadcrumbIconsInterface", { fg = csbase.cyan })
hi(0, "BreadcrumbIconsKey", { fg = csbase.blue })
hi(0, "BreadcrumbIconsKeyword", { fg = csbase.neon_red })
hi(0, "BreadcrumbIconsMethod", { fg = csbase.green })
hi(0, "BreadcrumbIconsModule", { fg = csbase.cyan })
hi(0, "BreadcrumbIconsNamespace", { fg = csbase.cyan })
hi(0, "BreadcrumbIconsNull", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsNumber", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsObject", { fg = csbase.cyan })
hi(0, "BreadcrumbIconsOperator", { fg = csbase.neon_red })
hi(0, "BreadcrumbIconsPackage", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsProperty", { fg = csbase.blue })
hi(0, "BreadcrumbIconsReference", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsSnippet", { fg = csbase.green })
hi(0, "BreadcrumbIconsString", { fg = csbase.yellow })
hi(0, "BreadcrumbIconsStruct", { fg = csbase.neon_red })
hi(0, "BreadcrumbIconsText", { fg = csbase.yellow })
hi(0, "BreadcrumbIconsTypeParameter", { fg = csbase.blue })
hi(0, "BreadcrumbIconsUnit", { fg = csbase.magenta })
hi(0, "BreadcrumbIconsVariable", { fg = csbase.cyan })
hi(0, "BufferLineBackground", { bg = "#0d0e0b", fg = "#989895", sp = "#151612" })
hi(0, "BufferLineBuffer", { bg = "#0f100d", fg = csbase.dimmed5 })
hi(0, "BufferLineBufferSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineBufferVisible", { bg = csbase.black, fg = "#c8c7c4", sp = "#151612" })
hi(0, "BufferLineCloseButton", { bg = "#0d0e0b", fg = csbase.text, sp = "#151612" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineCloseButtonVisible", { bg = csbase.black, fg = csbase.text, sp = "#151612" })
hi(0, "BufferLineDevIconConf", { bg = "#0f100d", fg = "#6d8086" })
hi(0, "BufferLineDevIconConfig", { bg = "#0f100d", fg = "#6d8086" })
hi(0, "BufferLineDevIconNix", { bg = "#0f100d", fg = "#7ebae4" })
hi(0, "BufferLineDevIconPySelected", { bg = "#151612", fg = "#ffbc03" })
hi(0, "BufferLineDevIconSh", { bg = "#0f100d", fg = "#4d5a5e" })
hi(0, "BufferLineDiagnostic", { bg = "#0f100d", fg = "#52544c" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#151612", fg = "#b7b7b4" })
hi(0, "BufferLineDiagnosticVisible", { bg = "#131410", fg = "#52544c" })
hi(0, "BufferLineDuplicate", { bg = "#0d0e0b", fg = "#60605d", sp = "#151612" })
hi(0, "BufferLineDuplicateSelected", { bg = "#151612", fg = "#9d1f4b", sp = "#151612" })
hi(0, "BufferLineDuplicateVisible", { bg = csbase.black, fg = "#898985", sp = "#151612" })
hi(0, "BufferLineError", { bg = "#0d0e0b", fg = "#9a1c48", sp = "#151612" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#0d0e0b", fg = "#771839", sp = "#151612" })
hi(0, "BufferLineErrorDiagnosticSelected", { bg = "#151612", fg = "#c0225a", sp = "#151612" })
hi(0, "BufferLineErrorDiagnosticVisible", { bg = csbase.black, fg = "#a52652", sp = "#151612" })
hi(0, "BufferLineErrorSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineErrorVisible", { bg = csbase.black, fg = "#cf2662", sp = "#151612" })
hi(0, "BufferLineFill", { bg = csbase.dark, sp = "#151612" })
hi(0, "BufferLineGroupLabel", { bg = csbase.dimmed5, fg = "#0b0c09" })
hi(0, "BufferLineGroupSeparator", { bg = "#0b0c09", fg = csbase.dimmed5 })
hi(0, "BufferLineHint", { link = "BufferLineInfo" })
hi(0, "BufferLineHintDiagnostic", { link = "BufferLineInfoDiagnostic" })
hi(0, "BufferLineHintDiagnosticSelected", { link = "BufferLineInfoDiagnosticSelected" })
hi(0, "BufferLineHintDiagnosticVisible", { link = "BufferLineInfoDiagnosticVisible" })
hi(0, "BufferLineHintSelected", { link = "BufferLineInfoSelected" })
hi(0, "BufferLineHintVisible", { link = "BufferLineInfoVisible" })
hi(0, "BufferLineIndicator", { bg = "#0d0e0b", fg = "#0d0e0b", sp = "#151612" })
hi(0, "BufferLineIndicatorSelected", { bg = "#151612", fg = csbase.yellow, sp = "#151612" })
hi(0, "BufferLineIndicatorVisible", { bg = csbase.black, fg = csbase.black, sp = "#151612" })
hi(0, "BufferLineInfo", { bg = "#0d0e0b", fg = "#649e9d", sp = "#151612" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#0d0e0b", fg = "#4e7a78", sp = "#151612" })
hi(0, "BufferLineInfoDiagnosticSelected", { bg = "#151612", fg = "#7bc4c3", sp = "#151612" })
hi(0, "BufferLineInfoDiagnosticVisible", { bg = csbase.black, fg = "#6ea9a6", sp = "#151612" })
hi(0, "BufferLineInfoSelected", { bg = "#151612", fg = csbase.cyan, sp = "#151612" })
hi(0, "BufferLineInfoVisible", { bg = csbase.black, fg = "#86d4d2", sp = "#151612" })
hi(0, "BufferLineModified", { bg = "#0d0e0b", fg = csbase.text, sp = "#151612" })
hi(0, "BufferLineModifiedSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineModifiedVisible", { bg = csbase.black, fg = csbase.text, sp = "#151612" })
hi(0, "BufferLineNumbers", { bg = "#0f100d", fg = csbase.dimmed5 })
hi(0, "BufferLineNumbersSelected", { bg = "#151612", fg = csbase.text })
hi(0, "BufferLineNumbersVisible", { bg = "#131410", fg = csbase.dimmed5 })
hi(0, "BufferLineOffsetSeparator", { link = "NeoTreeWinSeparator" })
hi(0, "BufferLinePick", { bg = "#0d0e0b", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLinePickSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLinePickVisible", { bg = csbase.black, fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineSeparator", { bg = "#0d0e0b", fg = csbase.dark, sp = "#151612" })
hi(0, "BufferLineSeparatorSelected", { bg = "#151612", fg = csbase.dark, sp = "#151612" })
hi(0, "BufferLineSeparatorVisible", { bg = csbase.black, fg = csbase.dark, sp = "#151612" })
hi(0, "BufferLineTab", { bg = "#0d0e0b", fg = "#989895", sp = "#151612" })
hi(0, "BufferLineTabClose", { bg = csbase.dark, fg = csbase.dark, sp = "#151612" })
hi(0, "BufferLineTabSelected", { bg = "#151612", fg = csbase.neon_red, sp = "#151612" })
hi(0, "BufferLineTabSeparator", { bg = "#0d0e0b", fg = "#0d0e0b", sp = "#151612" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#151612", fg = "#151612", sp = "#151612" })
hi(0, "BufferLineTruncMarker", { bg = "#0b0c09", fg = csbase.dimmed5 })
hi(0, "BufferLineWarning", { bg = "#0d0e0b", fg = "#9c6017", sp = "#151612" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#0d0e0b", fg = "#794b14", sp = "#151612" })
hi(0, "BufferLineWarningDiagnosticSelected", { bg = "#151612", fg = "#c3761b", sp = "#151612" })
hi(0, "BufferLineWarningDiagnosticVisible", { bg = csbase.black, fg = "#a76a20", sp = "#151612" })
hi(0, "BufferLineWarningSelected", { bg = "#151612", fg = csbase.orange, sp = "#151612" })
hi(0, "BufferLineWarningVisible", { bg = csbase.black, fg = "#d2801f", sp = "#151612" })
hi(0, "Character", { fg = csbase.magenta })
hi(0, "CmpItemAbbr", { fg = csbase.dimmed1 })
hi(0, "CmpItemAbbrDeprecated", { fg = csbase.dimmed1 })
hi(0, "CmpItemAbbrMatch", { fg = csbase.text })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemKindArray", { fg = csbase.neon_red })
hi(0, "CmpItemKindBoolean", { fg = csbase.neon_red })
hi(0, "CmpItemKindClass", { fg = csbase.cyan })
hi(0, "CmpItemKindColor", { fg = csbase.magenta })
hi(0, "CmpItemKindConstant", { fg = csbase.magenta })
hi(0, "CmpItemKindConstructor", { fg = csbase.green })
hi(0, "CmpItemKindEnum", { fg = csbase.blue })
hi(0, "CmpItemKindEnumMember", { fg = csbase.blue })
hi(0, "CmpItemKindEvent", { fg = csbase.blue })
hi(0, "CmpItemKindField", { fg = csbase.blue })
hi(0, "CmpItemKindFile", { fg = csbase.red })
hi(0, "CmpItemKindFolder", { fg = csbase.red })
hi(0, "CmpItemKindFunction", { fg = csbase.green })
hi(0, "CmpItemKindInterface", { fg = csbase.cyan })
hi(0, "CmpItemKindKey", { fg = csbase.blue })
hi(0, "CmpItemKindKeyword", { fg = csbase.neon_red })
hi(0, "CmpItemKindMethod", { fg = csbase.green })
hi(0, "CmpItemKindModule", { fg = csbase.cyan })
hi(0, "CmpItemKindNamespace", { fg = csbase.cyan })
hi(0, "CmpItemKindNull", { fg = csbase.magenta })
hi(0, "CmpItemKindNumber", { fg = csbase.magenta })
hi(0, "CmpItemKindObject", { fg = csbase.cyan })
hi(0, "CmpItemKindOperator", { fg = csbase.neon_red })
hi(0, "CmpItemKindPackage", { fg = csbase.magenta })
hi(0, "CmpItemKindProperty", { fg = csbase.blue })
hi(0, "CmpItemKindReference", { fg = csbase.magenta })
hi(0, "CmpItemKindSnippet", { fg = csbase.green })
hi(0, "CmpItemKindString", { fg = csbase.yellow })
hi(0, "CmpItemKindStruct", { fg = csbase.neon_red })
hi(0, "CmpItemKindText", { fg = csbase.yellow })
hi(0, "CmpItemKindTypeParameter", { fg = csbase.blue })
hi(0, "CmpItemKindUnit", { fg = csbase.magenta })
hi(0, "CmpItemKindVariable", { fg = csbase.cyan })
hi(0, "CmpItemMenu", { fg = "#b1b2a6" })
hi(0, "CocGitAddedSign", { bg = "#151612", fg = csbase.green })
hi(0, "CocGitChangeRemovedSign", { bg = "#151612", fg = csbase.neon_red })
hi(0, "CocGitChangedSign", { bg = "#151612", fg = csbase.yellow })
hi(0, "CocGitRemovedSign", { bg = "#151612", fg = csbase.neon_red })
hi(0, "CocGitTopRemovedSign", { bg = "#151612", fg = csbase.neon_red })
hi(0, "ColorColumn", { bg = csbase.dimmed8 })
hi(0, "Comment", { fg = "#5d5e58" })
hi(0, "Conceal", { bg = "#151612", fg = csbase.dimmed5 })
hi(0, "Conditional", { fg = csbase.neon_red })
hi(0, "Constant", { fg = csbase.magenta })
hi(0, "Cursor", { bg = csbase.text, fg = csbase.text })
hi(0, "CursorColumn", { bg = "#372913" })
hi(0, "CursorLine", { bg = "#372913" })
hi(0, "CursorLineFold", { bg = "#151612", fg = csbase.text })
hi(0, "CursorLineNr", { bg = "#151612", fg = csbase.red })
hi(0, "DashboardDesc", { fg = csbase.dimmed1 })
hi(0, "DashboardFiles", { fg = csbase.blue })
hi(0, "DashboardFooter", { fg = csbase.green })
hi(0, "DashboardHeader", { fg = csbase.yellow })
hi(0, "DashboardIcon", { fg = csbase.blue })
hi(0, "DashboardKey", { fg = csbase.cyan })
hi(0, "DashboardMruTitle", { fg = csbase.yellow })
hi(0, "DashboardProjectTitle", { fg = csbase.yellow })
hi(0, "DashboardShortcut", { fg = csbase.magenta })
hi(0, "Define", { fg = csbase.neon_red })
hi(0, "Delimiter", { fg = csbase.text })
hi(0, "DiagnosticError", { fg = csbase.neon_red })
hi(0, "DiagnosticHint", { fg = csbase.cyan })
hi(0, "DiagnosticInfo", { fg = csbase.cyan })
hi(0, "DiagnosticSignError", { fg = csbase.neon_red })
hi(0, "DiagnosticSignHint", { fg = csbase.cyan })
hi(0, "DiagnosticSignInfo", { fg = csbase.cyan })
hi(0, "DiagnosticSignWarn", { fg = csbase.orange })
hi(0, "DiagnosticUnderlineError", { sp = csbase.neon_red, undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = csbase.cyan, undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = csbase.cyan, undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = csbase.orange, undercurl = true })
hi(0, "DiagnosticUnnecessary", { sp = csbase.cyan, undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#3c272a", fg = csbase.neon_red })
hi(0, "DiagnosticVirtualTextHint", { bg = "#323d38", fg = csbase.cyan })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#323d38", fg = csbase.cyan })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#3c3321", fg = csbase.orange })
hi(0, "DiagnosticWarn", { fg = csbase.orange })
hi(0, "DiffAdd", { bg = "#43492f", fg = "#83ac2e" })
hi(0, "DiffChange", { bg = "#4b412e", fg = "#be7824" })
hi(0, "DiffDelete", { bg = "#4b3636", fg = "#bc2b5d" })
hi(0, "DiffText", { bg = "#151612", fg = csbase.text })
hi(0, "Directory", { bg = csbase.dark, fg = csbase.dimmed5 })
hi(0, "EndOfBuffer", { fg = "#151612" })
hi(0, "Error", { fg = csbase.neon_red })
hi(0, "ErrorMsg", { bg = "#151612", fg = csbase.neon_red })
hi(0, "Exception", { fg = csbase.neon_red })
hi(0, "FidgetTask", { bg = "#151612", fg = csbase.text })
hi(0, "FidgetTitle", { bg = "#151612", fg = csbase.yellow })
hi(0, "Float", { fg = csbase.magenta })
hi(0, "FloatBorder", { bg = "#151612", fg = csbase.dark })
hi(0, "FloatTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "FoldColumn", { bg = csbase.black, fg = csbase.dimmed1 })
hi(0, "Folded", { bg = "#636360" })
hi(0, "Function", { fg = csbase.orange })
hi(0, "FzfLuaBackdrop", { bg = csbase.black })
hi(0, "FzfLuaBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "FzfLuaCursorLine", { bg = "#2f312b" })
hi(0, "FzfLuaFzfHeader", { fg = "#afb0a6" })
hi(0, "FzfLuaFzfInfo", { fg = csbase.dimmed5 })
hi(0, "FzfLuaFzfPointer", { fg = csbase.blue })
hi(0, "FzfLuaHeaderBind", { fg = csbase.cyan })
hi(0, "FzfLuaHeaderText", { fg = csbase.green })
hi(0, "FzfLuaHelpBorder", { bg = "#151612", fg = csbase.green })
hi(0, "FzfLuaHelpNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "FzfLuaNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "FzfLuaPreviewBorder", { link = "FzfLuaBorder" })
hi(0, "FzfLuaPreviewNormal", { bg = "#151612" })
hi(0, "FzfLuaPreviewTitle", { bg = "#181915", fg = csbase.blue })
hi(0, "FzfLuaScrollBorderEmpty", { link = "FzfLuaBorder" })
hi(0, "FzfLuaScrollBorderFull", { link = "FzfLuaBorder" })
hi(0, "FzfLuaTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "GitConflictAncestor", { bg = "#68217a" })
hi(0, "GitConflictAncestorLabel", { bg = "#a634c3" })
hi(0, "GitConflictCurrent", { bg = "#151612" })
hi(0, "GitConflictCurrentLabel", { bg = "#21231c" })
hi(0, "GitConflictIncoming", { bg = "#43492f" })
hi(0, "GitConflictIncomingLabel", { bg = "#6b744b" })
hi(0, "GitSignsAdd", { link = "SignAdd" })
hi(0, "GitSignsAddInline", { link = "DiffAdd" })
hi(0, "GitSignsChange", { link = "SignChange" })
hi(0, "GitSignsChangeInline", { link = "DiffChange" })
hi(0, "GitSignsCurrentLineBlame", { fg = csbase.dimmed6 })
hi(0, "GitSignsDelete", { link = "SignDelete" })
hi(0, "GitSignsDeleteInline", { link = "DiffDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#537117" })
hi(0, "GitSignsStagedAddCul", { fg = "#537117" })
hi(0, "GitSignsStagedAddLn", { bg = "#43492f", fg = "#415617" })
hi(0, "GitSignsStagedAddNr", { fg = "#537117" })
hi(0, "GitSignsStagedChange", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedChangeCul", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedChangeLn", { bg = "#4b412e", fg = "#5f3c12" })
hi(0, "GitSignsStagedChangeNr", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedChangedelete", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#4b412e", fg = "#5f3c12" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#7e4b0f" })
hi(0, "GitSignsStagedDelete", { fg = "#7c1339" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#7c1339" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7c1339" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7c1339" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7c1339" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7c1339" })
hi(0, "GitSignsStagedUntracked", { fg = "#537117" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#537117" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#43492f", fg = "#415617" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#537117" })
hi(0, "IblIndent", { fg = csbase.dimmed6 })
hi(0, "IblScope", { bg = "#31322c", fg = "#b4b5a9" })
hi(0, "IblWhitespace", { fg = csbase.dimmed6 })
hi(0, "Identifier", { fg = csbase.text })
hi(0, "IncSearch", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "Include", { fg = csbase.neon_red })
hi(0, "IndentBlankLineIndent1", { fg = csbase.neon_red })
hi(0, "IndentBlankLineIndent2", { fg = csbase.orange })
hi(0, "IndentBlankLineIndent3", { fg = csbase.yellow })
hi(0, "IndentBlankLineIndent4", { fg = csbase.green })
hi(0, "IndentBlankLineIndent5", { fg = csbase.cyan })
hi(0, "IndentBlankLineIndent6", { fg = csbase.magenta })
hi(0, "IndentBlanklineChar", { fg = "#31322c" })
hi(0, "IndentBlanklineContextChar", { fg = csbase.orange })
hi(0, "IndentBlanklineContextStart", { sp = csbase.orange, underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#31322c" })
hi(0, "Keyword", { fg = csbase.neon_red })
hi(0, "Label", { fg = csbase.neon_red })
hi(0, "LazyButton", { bg = csbase.dimmed8, fg = csbase.dimmed1 })
hi(0, "LazyButtonActive", { bg = csbase.dimmed6, fg = csbase.dimmed1 })
hi(0, "LazyComment", { fg = csbase.yellow })
hi(0, "LazyDir", { link = "LazyUrl" })
hi(0, "LazyH1", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "LazyH2", { fg = csbase.green })
hi(0, "LazyNormal", { bg = "#2c2d27", fg = "#96978d" })
hi(0, "LazyProgressDone", { bg = "#2c2d27", fg = csbase.yellow })
hi(0, "LazyProgressTodo", { bg = "#2c2d27", fg = csbase.dimmed3 })
hi(0, "LazyProp", { bg = "#2c2d27", fg = csbase.green })
hi(0, "LazyReasonCmd", { fg = csbase.cyan })
hi(0, "LazyReasonStart", { fg = csbase.green })
hi(0, "LazySpecial", { fg = csbase.yellow })
hi(0, "LazyUrl", { fg = csbase.cyan })
hi(0, "LineNr", { bg = "#31322c", fg = "#b4b5a9" })
hi(0, "LocalHighlight", { bg = "#664316" })
hi(0, "Macro", { fg = csbase.neon_red })
hi(0, "MatchParen", { fg = csbase.yellow, underline = true })
hi(0, "MiniIndentscopeSymbol", { fg = csbase.orange })
hi(0, "MiniStatuslineModeCommand", { bg = csbase.neon_red, fg = csbase.dark })
hi(0, "MiniStatuslineModeInsert", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "MiniStatuslineModeNormal", { bg = csbase.green, fg = csbase.dark })
hi(0, "MiniStatuslineModeOther", { bg = csbase.text, fg = csbase.dark })
hi(0, "MiniStatuslineModeReplace", { bg = csbase.blue, fg = csbase.dark })
hi(0, "MiniStatuslineModeVisual", { bg = csbase.cyan, fg = csbase.dark })
hi(0, "ModeMsg", { bg = "#151612", fg = csbase.text })
hi(0, "MoreMsg", { fg = csbase.yellow })
hi(0, "MsgArea", { link = "ModeMsg" })
hi(0, "MsgSeparator", { link = "ModeMsg" })
hi(0, "NoiceCmdlineIconSearch", { fg = csbase.blue })
hi(0, "NoiceCmdlinePopup", { bg = "#151612" })
hi(0, "NoiceCmdlinePopupBorder", { bg = "#151612", fg = csbase.dimmed1 })
hi(0, "NoiceCmdlinePopupBorderSearch", { bg = "#151612", fg = csbase.blue })
hi(0, "NoiceConfirm", { bg = csbase.dimmed8, fg = csbase.dimmed1 })
hi(0, "NoiceConfirmBorder", { bg = csbase.dimmed8, fg = csbase.dimmed8 })
hi(0, "NoiceFormatConfirm", { bg = csbase.dimmed8, fg = csbase.dimmed1 })
hi(0, "NoiceFormatConfirmDefault", { bg = csbase.dimmed6, fg = csbase.dimmed1 })
hi(0, "NoiceFormatProgressDone", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "NoiceFormatProgressTodo", { bg = csbase.dimmed5, fg = csbase.dimmed8 })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NoiceLspProgressClient", { fg = csbase.cyan })
hi(0, "NoiceLspProgressTitle", { fg = csbase.dimmed3 })
hi(0, "NoiceMini", { fg = csbase.dimmed6 })
hi(0, "NoiceSplit", { bg = "#151612" })
hi(0, "NonText", { fg = "#151612" })
hi(0, "Normal", { bg = "#151612", fg = csbase.text })
hi(0, "NormalFloat", { bg = csbase.dark, fg = csbase.dimmed1 })
hi(0, "NormalNC", { bg = "#151612", fg = csbase.text })
hi(0, "NotifyBackground", { link = "Normal" })
hi(0, "NotifyDEBUGBody", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#464740" })
hi(0, "NotifyDEBUGIcon", { fg = csbase.text })
hi(0, "NotifyDEBUGTitle", { fg = csbase.dimmed3 })
hi(0, "NotifyERRORBody", { link = "Normal" })
hi(0, "NotifyERRORBorder", { fg = "#662739" })
hi(0, "NotifyERRORIcon", { fg = csbase.neon_red })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORIcon" })
hi(0, "NotifyINFOBody", { link = "Normal" })
hi(0, "NotifyINFOBorder", { fg = "#4a6864" })
hi(0, "NotifyINFOIcon", { fg = csbase.cyan })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOIcon" })
hi(0, "NotifyTRACEBody", { link = "Normal" })
hi(0, "NotifyTRACEBorder", { fg = "#4f4264" })
hi(0, "NotifyTRACEIcon", { fg = csbase.magenta })
hi(0, "NotifyTRACETitle", { fg = csbase.magenta })
hi(0, "NotifyWARNBody", { link = "Normal" })
hi(0, "NotifyWARNBorder", { fg = "#674921" })
hi(0, "NotifyWARNIcon", { fg = csbase.orange })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNIcon" })
hi(0, "Number", { fg = csbase.magenta })
hi(0, "NvimTreeCursorLine", { link = "CursorLine" })
hi(0, "NvimTreeEmptyFolderName", { fg = csbase.dimmed3 })
hi(0, "NvimTreeEndOfBuffer", { bg = csbase.dark, fg = csbase.dark })
hi(0, "NvimTreeExecFile", { fg = csbase.green })
hi(0, "NvimTreeFolderIcon", { fg = csbase.dimmed3 })
hi(0, "NvimTreeFolderName", { fg = csbase.dimmed3 })
hi(0, "NvimTreeGitDeleted", { fg = csbase.neon_red })
hi(0, "NvimTreeGitDeletedIcon", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitDirty", { fg = csbase.yellow })
hi(0, "NvimTreeGitDirtyIcon", { link = "NvimTreeGitDirty" })
hi(0, "NvimTreeGitIgnored", { fg = csbase.dimmed6 })
hi(0, "NvimTreeGitIgnoredIcon", { link = "NvimTreeGitIgnored" })
hi(0, "NvimTreeGitMerge", { fg = csbase.orange })
hi(0, "NvimTreeGitMergeIcon", { link = "NvimTreeGitMerge" })
hi(0, "NvimTreeGitNew", { fg = csbase.dimmed3 })
hi(0, "NvimTreeGitNewIcon", { link = "NvimTreeGitNew" })
hi(0, "NvimTreeGitRenamed", { fg = csbase.dimmed3 })
hi(0, "NvimTreeGitRenamedIcon", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeGitStaged", { fg = csbase.yellow })
hi(0, "NvimTreeGitStagedIcon", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeGitignoreIcon", { fg = csbase.dimmed6 })
hi(0, "NvimTreeImageFile", { fg = csbase.text })
hi(0, "NvimTreeIndentMarker", { link = "IndentBlanklineChar" })
hi(0, "NvimTreeNormal", { bg = csbase.background, fg = csbase.dimmed3 })
hi(0, "NvimTreeOpenedFolderName", { fg = csbase.dimmed3 })
hi(0, "NvimTreeRootFolder", { fg = csbase.dimmed1 })
hi(0, "NvimTreeSpecialFile", { fg = csbase.text })
hi(0, "NvimTreeSymlink", { fg = csbase.text })
hi(0, "NvimTreeWinSeparator", { bg = csbase.background, fg = csbase.background })
hi(0, "NvimTreeWindowPicker", { bg = "#4493c8", ctermbg = 4, ctermfg = 15, fg = "#ededed" })
hi(0, "Offset", { bg = csbase.black, fg = csbase.dimmed6, sp = "#151612" })
hi(0, "Operator", { fg = csbase.neon_red })
hi(0, "Pmenu", { bg = csbase.dimmed8, fg = csbase.dimmed1 })
hi(0, "PmenuSbar", { bg = "#31322b" })
hi(0, "PmenuSel", { bg = csbase.dimmed5 })
hi(0, "PmenuThumb", { bg = "#2e2f2a" })
hi(0, "PreCondit", { fg = csbase.neon_red })
hi(0, "PreProc", { fg = csbase.yellow })
hi(0, "RainbowDelimiterBlue", { fg = csbase.blue })
hi(0, "RainbowDelimiterCyan", { fg = csbase.cyan })
hi(0, "RainbowDelimiterGreen", { fg = csbase.green })
hi(0, "RainbowDelimiterOrange", { fg = csbase.orange })
hi(0, "RainbowDelimiterRed", { fg = csbase.neon_red })
hi(0, "RainbowDelimiterViolet", { fg = csbase.magenta })
hi(0, "RainbowDelimiterYellow", { fg = csbase.yellow })
hi(0, "RenamerBorder", { bg = "#151612", fg = csbase.dimmed1 })
hi(0, "RenamerNormal", { bg = "#151612" })
hi(0, "RenamerTitle", { fg = csbase.yellow })
hi(0, "Repeat", { fg = csbase.neon_red })
hi(0, "SPCursorLine", { bg = "#b4b5a9", fg = csbase.yellow })
hi(0, "SPFloatBorder", { bg = "#151612", fg = csbase.dimmed8 })
hi(0, "SPNormalFloat", { bg = csbase.dimmed8, fg = csbase.dimmed1 })
hi(0, "SPTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "ScrollbarCursor", { bg = "#3d3e38", fg = "#3d3e38" })
hi(0, "ScrollbarCursorHandle", { bg = "#2e2f2a" })
hi(0, "ScrollbarError", { bg = "#151612", fg = csbase.neon_red })
hi(0, "ScrollbarErrorHandle", { bg = "#2e2f2a", fg = csbase.neon_red })
hi(0, "ScrollbarGitAdd", { bg = "#151612", fg = csbase.green })
hi(0, "ScrollbarGitAddHandle", { bg = "#2e2f2a", fg = csbase.green })
hi(0, "ScrollbarGitChange", { bg = "#151612", fg = csbase.yellow })
hi(0, "ScrollbarGitChangeHandle", { bg = "#2e2f2a", fg = csbase.yellow })
hi(0, "ScrollbarGitDelete", { bg = "#151612", fg = csbase.neon_red })
hi(0, "ScrollbarGitDeleteHandle", { bg = "#2e2f2a", fg = csbase.neon_red })
hi(0, "ScrollbarHandle", { bg = "#2e2f2a", fg = csbase.text })
hi(0, "ScrollbarHint", { bg = "#151612", fg = csbase.cyan })
hi(0, "ScrollbarHintHandle", { bg = "#2e2f2a", fg = csbase.cyan })
hi(0, "ScrollbarInfo", { bg = "#151612", fg = csbase.cyan })
hi(0, "ScrollbarInfoHandle", { bg = "#2e2f2a", fg = csbase.cyan })
hi(0, "ScrollbarSearch", { bg = "#151612", fg = csbase.text })
hi(0, "ScrollbarSearchHandle", { bg = "#2e2f2a" })
hi(0, "ScrollbarWarn", { bg = "#151612", fg = csbase.orange })
hi(0, "ScrollbarWarnHandle", { bg = "#2e2f2a", fg = csbase.orange })
hi(0, "Search", { bg = "#664316" })
hi(0, "SignAdd", { fg = csbase.green })
hi(0, "SignChange", { fg = csbase.orange })
hi(0, "SignColumn", { bg = csbase.background })
hi(0, "SignDelete", { fg = csbase.neon_red })
hi(0, "SnacksDashboardDesc", { fg = csbase.dimmed1 })
hi(0, "SnacksDashboardIcon", { fg = csbase.blue })
hi(0, "SnacksDashboardNormal", { bg = "#151612", fg = csbase.text })
hi(0, "Special", { fg = csbase.neon_red })
hi(0, "SpecialChar", { fg = csbase.neon_red })
hi(0, "SpecialComment", { fg = csbase.dimmed5 })
hi(0, "SpellBad", { fg = csbase.neon_red, sp = csbase.neon_red, undercurl = true })
hi(0, "SpellCap", { fg = csbase.neon_red, sp = csbase.neon_red, undercurl = true })
hi(0, "SpellLocal", { fg = csbase.neon_red, sp = csbase.neon_red, undercurl = true })
hi(0, "SpellRare", { fg = csbase.neon_red, sp = csbase.neon_red, undercurl = true })
hi(0, "Statement", { fg = csbase.magenta })
hi(0, "StatusLine", { bg = csbase.black, fg = csbase.dimmed1 })
hi(0, "StatusLineNC", { bg = csbase.black, fg = csbase.dimmed5 })
hi(0, "StatusLineSeparator", { fg = csbase.black })
hi(0, "StatusLineTerm", { fg = csbase.black })
hi(0, "StatusLineTermNC", { fg = csbase.black })
hi(0, "StorageClass", { fg = csbase.neon_red })
hi(0, "String", { fg = csbase.yellow })
hi(0, "Structure", { fg = csbase.cyan })
hi(0, "TSRainbowBlue", { fg = csbase.blue })
hi(0, "TSRainbowCyan", { fg = csbase.cyan })
hi(0, "TSRainbowGreen", { fg = csbase.green })
hi(0, "TSRainbowOrange", { fg = csbase.orange })
hi(0, "TSRainbowRed", { fg = csbase.neon_red })
hi(0, "TSRainbowViolet", { fg = csbase.magenta })
hi(0, "TSRainbowYellow", { fg = csbase.yellow })
hi(0, "TabLine", { link = "BufferLineBackground" })
hi(0, "TabLineFill", { link = "BufferLineFill" })
hi(0, "TabLineSel", { link = "BufferLineTabSelected" })
hi(0, "TelescopeBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "TelescopeMatching", { fg = csbase.blue })
hi(0, "TelescopeNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "TelescopePreviewBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "TelescopePreviewLine", { link = "TelescopeSelection" })
hi(0, "TelescopePreviewNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "TelescopePreviewTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "TelescopePromptBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "TelescopePromptCounter", { fg = csbase.neon_red })
hi(0, "TelescopePromptNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "TelescopePromptPrefix", { fg = csbase.cyan })
hi(0, "TelescopePromptTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "TelescopeResultsBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "TelescopeResultsNormal", { bg = "#151612", fg = "#afb0a6" })
hi(0, "TelescopeResultsTitle", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "TelescopeSelection", { bg = "#2f312b" })
hi(0, "TelescopeSelectionCaret", { bg = "#2f312b" })
hi(0, "TermCursor", { bg = csbase.text, fg = "#ffffff" })
hi(0, "Title", { fg = csbase.yellow })
hi(0, "Todo", { bg = "#151612", fg = csbase.magenta })
hi(0, "ToggleTerm", { bg = "#151612", fg = csbase.text })
hi(0, "ToggleTermBorder", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "ToggleTermNormal", { bg = "#151612", fg = csbase.text })
hi(0, "Type", { fg = csbase.text })
hi(0, "Typedef", { fg = csbase.neon_red })
hi(0, "UfoFoldedBg", { bg = "#151612" })
hi(0, "VertSplit", { bg = "#151612", fg = csbase.dark })
hi(0, "Visual", { bg = "#50514b" })
hi(0, "VisualEOL", { ctermfg = 121, fg = "#90ee90" })
hi(0, "VisualNoEOL", { ctermfg = 9, fg = "#ff0000" })
hi(0, "WarningMsg", { fg = csbase.orange })
hi(0, "WhichKey", { fg = csbase.blue })
hi(0, "WhichKeyBorder", { bg = csbase.dimmed8, fg = csbase.dimmed8 })
hi(0, "WhichKeyDesc", { fg = csbase.yellow })
hi(0, "WhichKeyGroup", { fg = csbase.magenta })
hi(0, "WhichKeyNormal", { bg = csbase.dimmed8 })
hi(0, "WhichKeySeperator", { fg = csbase.neon_red })
hi(0, "Whitespace", { fg = csbase.dimmed6 })
hi(0, "WildMenu", { bg = csbase.yellow, fg = csbase.dark })
hi(0, "WinBar", { bg = "#151612", fg = csbase.dimmed3 })
hi(0, "WinSeparator", { fg = csbase.dark })
hi(0, "diffAdded", { fg = csbase.green })
hi(0, "diffChanged", { fg = csbase.yellow })
hi(0, "diffFile", { fg = csbase.yellow })
hi(0, "diffLine", { fg = csbase.cyan })
hi(0, "diffNewFile", { fg = csbase.yellow })
hi(0, "diffRemoved", { fg = csbase.neon_red })
hi(0, "healthError", { fg = csbase.neon_red })
hi(0, "healthSuccess", { fg = csbase.green })
hi(0, "healthWarning", { fg = csbase.blue })
hi(0, "javaAnnotation", { fg = csbase.dimmed3 })
hi(0, "lCursor", { bg = csbase.text, fg = "#151612" })
hi(0, "packerFail", { bg = csbase.dimmed8, fg = csbase.neon_red })
hi(0, "packerHash", { fg = csbase.blue })
hi(0, "packerOutput", { fg = csbase.yellow })
hi(0, "packerRelDate", { fg = csbase.magenta })
hi(0, "packerStatusFail", { bg = csbase.dimmed8, fg = csbase.neon_red })
hi(0, "packerStatusSuccess", { fg = csbase.green })
hi(0, "packerString", { fg = csbase.blue })
hi(0, "packerSuccess", { fg = csbase.green })

hi(0, "gotplAction", { link = "Keyword" })


-- Terminal colors
local g = vim.g

g.terminal_color_0 = csbase.dark
g.terminal_color_1 = csbase.neon_red
g.terminal_color_2 = csbase.green
g.terminal_color_3 = csbase.yellow
g.terminal_color_4 = csbase.blue
g.terminal_color_5 = csbase.magenta
g.terminal_color_6 = csbase.cyan
g.terminal_color_7 = csbase.text
g.terminal_color_8 = csbase.dimmed5
g.terminal_color_9 = csbase.neon_red
g.terminal_color_10 = csbase.green
g.terminal_color_11 = csbase.yellow
g.terminal_color_12 = csbase.blue
g.terminal_color_13 = csbase.magenta
g.terminal_color_14 = csbase.cyan
g.terminal_color_15 = csbase.text

