return {
  { "nvimdev/dashboard-nvim", enabled = false },
  { "saadparwaiz1/cmp_luasnip", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "hrsh7th/cmp-nvim-lsp", enabled = false },
  { "hrsh7th/cmp-buffer", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "williamboman/mason-lspconfig.nvim", enabled = false },
  { "williamboman/mason.nvim", enabled = false, build = nil },
  { "MagicDuck/grug-far.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.base16", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.icons", enabled = false },
  -- { "echasnovski/mini.surround", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "folke/neodev.nvim", enabled = false },
  { "folke/lazydev.nvim", enabled = false },
  { "hrsh7th/nvim-cmp", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "neovim/nvim-lspconfig", enabled = false, event = {}, opts = nil, config = nil },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  --{ "RRethy/vim-illuminate", enabled = false },
  { "catppuccin/nvim", enabled = false },
  -- { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "mason.nvim", enabled = false },
  { "trouble.nvim", enabled = false },
  { "saghen/blink.cmp", enabled = false },
  { "snacks.nvim",
    opts = {
      animate = { enabled = false },
      chunk = { enabled = false },
      indent = { enabled = false },
      input = { enabled = false },
      notifier = { enabled = false },
      scope = { enabled = false },
      scroll = { enabled = false },
      statuscolumn = { enabled = false }, -- we set this in options.lua
      toggle = { map = LazyVim.safe_keymap_set },
      words = { enabled = false },
    },
  },
}
