return {
  "nvim-treesitter/nvim-treesitter",
  --lazy = false,
  --priority = 500,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "diff",
      "dockerfile",
      "go",
      "hcl",
      "html",
      "javascript",
      "jq",
      "json",
      "json5",
      "jsonc",
      "kconfig",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "ninja",
      "perl",
      "php",
      "phpdoc",
      "python",
      "regex",
      "rst",
      "ruby",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
    },
    sync_install = false,
    highlight = { enable = true, use_languagetree = true, },
    indent = { enable = true },
    context_commentstring = { enable = true },
    --parser_install_dir = vim.fn.stdpath("config") .. "/treesitter_parsers",
  },
}
