[tools]
jq = "latest"
neovim = "stable"
sops = "latest"
usage = "latest"
yq = "latest"
pnpm = "latest"
node = "latest"
shfmt = "latest"
git = "latest"
kind = "0.24.0"
kubectl = "1.31.2"
pipx = "1.7.1"
helm = "3.16.2"

