[tools]
jq = "latest"
kubectl = "1.28.7"
neovim = "stable"
pipx = "1.4.3"
sops = "latest"
usage = "latest"
yq = "latest"
pnpm = "latest"
node = "latest"
shfmt = "latest"
helm = "3.15.4"
git = "latest"

